apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: grade-submission-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 32001
